package com.bzh.sportrecord.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bzh.sportrecord.greenModel.FriendsInfo;
import com.bzh.sportrecord.greenModel.MessageInfo;

import com.bzh.sportrecord.greenDao.FriendsInfoDao;
import com.bzh.sportrecord.greenDao.MessageInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsInfoDaoConfig;
    private final DaoConfig messageInfoDaoConfig;

    private final FriendsInfoDao friendsInfoDao;
    private final MessageInfoDao messageInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsInfoDaoConfig = daoConfigMap.get(FriendsInfoDao.class).clone();
        friendsInfoDaoConfig.initIdentityScope(type);

        messageInfoDaoConfig = daoConfigMap.get(MessageInfoDao.class).clone();
        messageInfoDaoConfig.initIdentityScope(type);

        friendsInfoDao = new FriendsInfoDao(friendsInfoDaoConfig, this);
        messageInfoDao = new MessageInfoDao(messageInfoDaoConfig, this);

        registerDao(FriendsInfo.class, friendsInfoDao);
        registerDao(MessageInfo.class, messageInfoDao);
    }
    
    public void clear() {
        friendsInfoDaoConfig.clearIdentityScope();
        messageInfoDaoConfig.clearIdentityScope();
    }

    public FriendsInfoDao getFriendsInfoDao() {
        return friendsInfoDao;
    }

    public MessageInfoDao getMessageInfoDao() {
        return messageInfoDao;
    }

}
