package com.bzh.sportrecord.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bzh.sportrecord.greenModel.FriendsInfo;

import com.bzh.sportrecord.greenDao.FriendsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsInfoDaoConfig;

    private final FriendsInfoDao friendsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsInfoDaoConfig = daoConfigMap.get(FriendsInfoDao.class).clone();
        friendsInfoDaoConfig.initIdentityScope(type);

        friendsInfoDao = new FriendsInfoDao(friendsInfoDaoConfig, this);

        registerDao(FriendsInfo.class, friendsInfoDao);
    }
    
    public void clear() {
        friendsInfoDaoConfig.clearIdentityScope();
    }

    public FriendsInfoDao getFriendsInfoDao() {
        return friendsInfoDao;
    }

}
